name: macOS_arm
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  gnat_gprbuild:
    name: GNAT macOS
    runs-on: macos-14
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2

    - name: Install texinfo with Homebrew
      run: brew install texinfo

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.11

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install e3-core==22.1.0

    - name: Build GPRbuild
      run: ./anod build gprbuild -v --loglevel DEBUG --enable-cleanup

    - name: Package GPRbuild
      run: ./anod build release_package --qualifier=package=gprbuild -v --loglevel DEBUG
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # for GitHub CLI tool

    - uses: actions/upload-artifact@v2
      with:
        name: anod-artifacts
        path: out_artifacts/*
        retention-days: 1

    - uses: actions/upload-artifact@v2
      with:
        name: release-packages
        path: sbx/*/release_package*/install/*
        retention-days: 5
