name: GNAT Windows
'on':
  pull_request:
    paths-ignore:
    - generate/**
    - utils/**
    - LICENSE
    - README.md
    - .gitignore
  workflow_dispatch:
    inputs:
      do_gh_release:
        description: Set to true to publish results in a GitHub release
        type: boolean
        required: false
        default: false
jobs:
  gcc_dependencies:
    name: GCC Dependencies WindowsMsys2
    runs-on: windows-11-arm
    env:
      CONFIG_SHELL: /bin/bash
      msystem: CLANGARM64
    defaults:
      run:
        shell: C:/msys64/usr/bin/bash {0}
        # shell: msys2 {0}
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Check architecture
      shell: pwsh
      run: |
        $env:PROCESSOR_ARCHITECTURE
        systeminfo | findstr /C:"System Type"
    - name: Extract gnat
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://github.com/reznikmm/mingw-woarm64-build/releases/download/gnat_20250131_0/native-aarch64-w64-mingw32-msvcrt.tar.gz" -OutFile gnat.tar.gz
        tar xzf gnat.tar.gz
        "$PWD\native-aarch64-w64-mingw32-msvcrt\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Extract gnatmake
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://github.com/reznikmm/mingw-woarm64-build/releases/download/gnat_20250131_0/gnatmake.tar.gz" -OutFile gnatmake.tar.gz
        tar xzvf gnatmake.tar.gz -C "native-aarch64-w64-mingw32-msvcrt/bin"

    - name: Use gnat
      continue-on-error: true
      shell: pwsh
      run: |
        gnatmake.exe --version

    - name: Check gnat1 dependencies
      shell: pwsh
      run: |
        cd $PWD\native-aarch64-w64-mingw32-msvcrt\bin\
        & objdump.exe -p ../lib/gcc/aarch64-w64-mingw32/15.0.1/gnat1.exe | Select-String "DLL Name"        

    - name: Try gnat
      continue-on-error: true
      shell: pwsh
      run: |
        cd $PWD\native-aarch64-w64-mingw32-msvcrt\bin\
        @"
        with Ada.Text_IO;
        procedure Hello is
        begin
           Ada.Text_IO.Put_Line ("Hello");
        end;
        "@ | Out-File -Encoding ASCII hello.adb
        Get-Content hello.adb
        gcc.exe -v -c hello.adb
        Write-Host "Exit code: $LASTEXITCODE"
        & ../lib/gcc/aarch64-w64-mingw32/15.0.1/gnat1.exe hello.adb -o ccoRFUuO.s
        Write-Host "Exit code: $LASTEXITCODE"
        & ls -l *
        gnatmake.exe -vh hello.adb -cargs -v
        gnatmake.exe -vh --GCC=gcc.exe hello.adb
        .\hello.exe

    - name: Download MSYS2 ARM64
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://github.com/msys2/msys2-installer/releases/download/2025-12-13/msys2-arm64-20251213.exe" -OutFile msys2-arm64-20251213.exe
        .\msys2-arm64-20251213.exe in --confirm-command --accept-messages --root C:/msys64
        
    # - name: Install msys2
    #   uses: msys2/setup-msys2@v2
    #   with:
    #     msystem: CLANGARM64
    #     install: |-
    #       base-devel
    #       git
    #       rsync
    #       mingw-w64-clang-aarch64-python
    #       mingw-w64-clang-aarch64-python-pip
    #       mingw-w64-clang-aarch64-python-psutil

    - name: Try gprbuild
      continue-on-error: true
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://github.com/alire-project/GNAT-FSF-builds/releases/download/gprbuild-25.0.0-1/gprbuild-x86_64-windows64-25.0.0-1.tar.gz" -OutFile gprbuild-x86_64-windows64-25.0.0-1.tar.gz
        tar xzf gprbuild-x86_64-windows64-25.0.0-1.tar.gz
        "$PWD\gprbuild-x86_64-windows64-25.0.0-1\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Try gprbuild
      continue-on-error: true
      shell: pwsh
      run: |
        gprconfig.exe --show-targets || true
        gprbuild.exe -vh --target=aarch64-w64-mingw32 hello.adb || true
        gprbuild.exe -vh hello.adb || true
        .\hello.exe

    - name: Enable Windows-On-ARM MSYS repo
      run: |-
        pacman -S --noconfirm patch
        patch /etc/pacman.conf 0002-add-woarm64-native-repository.patch
        pacman -Sy
        uname -a
        pacman -S --noconfirm mingw-w64-aarch64-toolchain
        pacman -Ss mingw-w64-aarch64-python || true
        pacman -Ss aarch64-python || true
    - name: Try gnat
      run: |-
        cat > hello.adb <<-EOF
        with Ada.Text_IO;
        procedure Hello is
        begin
           Ada.Text_IO.Put_Line ("Hello");
        end;
        EOF
        cat hello.adb
        gnatmake.exe hello.adb && ./hello

    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0

    - name: Prepare msys2 build setup
      run: |-
        df -h
        mkdir C:/aaa
        mount C:/aaa /aaa
        cd ..
        cp -r GNAT-FSF-builds /aaa
    - name: Build GMP
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build gmp -v --loglevel DEBUG --enable-cleanup
    - name: Build MPFR
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build mpfr -v --loglevel DEBUG --enable-cleanup
    - name: Build MPC
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build mpc -v --loglevel DEBUG --enable-cleanup
    - name: Build ISL
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build isl -v --loglevel DEBUG --enable-cleanup
    - name: Upload artifact 'gcc-dependencies-artifacts'
      uses: actions/upload-artifact@v4
      with:
        name: gcc-dependencies-artifacts
        path: C:/aaa/GNAT-FSF-builds/out_artifacts/*
        retention-days: 1
  gnat:
    needs:
    - gcc_dependencies
    name: GNAT WindowsMsys2
    runs-on: windows-2022
    env:
      CONFIG_SHELL: /bin/bash
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Install msys2
      uses: msys2/setup-msys2@v2
      with:
        install: |-
          base-devel
          git
          rsync
          mingw-w64-x86_64-github-cli
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-python
          mingw-w64-x86_64-python-pip
          mingw-w64-x86_64-python-psutil
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Prepare msys2 build setup
      run: |-
        df -h
        mkdir C:/aaa
        mount C:/aaa /aaa
        cd ..
        cp -r GNAT-FSF-builds /aaa
    - name: Download artifact 'gcc-dependencies-artifacts'
      uses: actions/download-artifact@v4
      with:
        name: gcc-dependencies-artifacts
        path: C:/aaa/GNAT-FSF-builds/in_artifacts/
    - name: Build GNAT native
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build gcc -v --loglevel DEBUG --enable-cleanup
    - name: Build GDB
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build gdb -v --loglevel DEBUG --enable-cleanup
    - name: Package GNAT
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build release_package --qualifier=package=gnat -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNAT
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build release_github --qualifier=package=gnat -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnat-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gnat-release-packages
        path: C:/aaa/GNAT-FSF-builds/sbx/*/release_package*/install/*
        retention-days: 5
  gprbuild:
    if: false
    name: GPRbuild WindowsMsys2
    runs-on: windows-2022
    env:
      CONFIG_SHELL: /bin/bash
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Install msys2
      uses: msys2/setup-msys2@v2
      with:
        install: |-
          base-devel
          git
          rsync
          mingw-w64-x86_64-github-cli
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-python
          mingw-w64-x86_64-python-pip
          mingw-w64-x86_64-python-psutil
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Prepare msys2 build setup
      run: |-
        df -h
        mkdir C:/aaa
        mount C:/aaa /aaa
        cd ..
        cp -r GNAT-FSF-builds /aaa
    - name: Build GPRbuild
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build gprbuild -v --loglevel DEBUG --enable-cleanup
    - name: Package GPRbuild
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build release_package --qualifier=package=gprbuild -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GPRbuild
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build release_github --qualifier=package=gprbuild -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gprbuild-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gprbuild-release-packages
        path: C:/aaa/GNAT-FSF-builds/sbx/*/release_package*/install/*
        retention-days: 5
  gnat_cross:
    if: false
    strategy:
      fail-fast: false
      matrix:
        target:
        - arm-elf
        - aarch64-elf
        - riscv64-elf
        - x86_64-elf
        - avr-elf
        - xtensa-esp32-elf
    needs:
    - gcc_dependencies
    name: GNAT ${{ matrix.target }} WindowsMsys2
    runs-on: windows-2022
    env:
      CONFIG_SHELL: /bin/bash
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Install msys2
      uses: msys2/setup-msys2@v2
      with:
        install: |-
          base-devel
          git
          rsync
          mingw-w64-x86_64-github-cli
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-python
          mingw-w64-x86_64-python-pip
          mingw-w64-x86_64-python-psutil
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Prepare msys2 build setup
      run: |-
        df -h
        mkdir C:/aaa
        mount C:/aaa /aaa
        cd ..
        cp -r GNAT-FSF-builds /aaa
    - name: Download artifact 'gcc-dependencies-artifacts'
      uses: actions/download-artifact@v4
      with:
        name: gcc-dependencies-artifacts
        path: C:/aaa/GNAT-FSF-builds/in_artifacts/
    - name: Build GNAT ${{ matrix.target }}
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build gcc --target=${{ matrix.target }} -v --loglevel DEBUG --enable-cleanup
    - name: Build GDB ${{ matrix.target }}
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build gdb --target=${{ matrix.target}} -v --loglevel DEBUG --enable-cleanup
    - name: Package GNAT ${{ matrix.target }}
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build release_package --qualifier=package=gnat --target=${{ matrix.target }} -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNAT ${{ matrix.target }}
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build release_github --qualifier=package=gnat --target=${{ matrix.target }} -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnat-release-packages-${{matrix.target}}'
      uses: actions/upload-artifact@v4
      with:
        name: gnat-release-packages-${{matrix.target}}
        path: C:/aaa/GNAT-FSF-builds/sbx/*/release_package*/install/*
  spark:
    if: false
    name: SPARK WindowsMsys2
    runs-on: windows-2022
    env:
      CONFIG_SHELL: /bin/bash
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Install msys2
      uses: msys2/setup-msys2@v2
      with:
        install: |-
          base-devel
          git
          rsync
          mingw-w64-x86_64-github-cli
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-python
          mingw-w64-x86_64-python-pip
          mingw-w64-x86_64-python-psutil
    - name: Install Python dependencies
      run: |-
        python3 -m pip install --upgrade pip
        pip install --break-system-packages e3-core==22.10.0
    - name: Prepare msys2 build setup
      run: |-
        df -h
        mkdir C:/aaa
        mount C:/aaa /aaa
        cd ..
        cp -r GNAT-FSF-builds /aaa
    - name: Build SPARK
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build spark2014 -v --loglevel DEBUG --enable-cleanup
    - name: Package GNATprove
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build release_package --qualifier=package=gnatprove -v --loglevel DEBUG
    - if: inputs.do_gh_release
      name: Release GNATprove
      run: mount C:/aaa /aaa && cd /aaa/GNAT-FSF-builds && python3 ./anod build release_github --qualifier=package=gnatprove -v --loglevel DEBUG --enable-cleanup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact 'gnatprove-release-packages'
      uses: actions/upload-artifact@v4
      with:
        name: gnatprove-release-packages
        path: C:/aaa/GNAT-FSF-builds/sbx/*/release_package*/install/*
        retention-days: 5
